import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.goto("http://localhost:5173/", { waitUntil: "networkidle" });
await page.click("#s-new");
await page.waitForFunction(() => (window).__paldyson?.world, null, { timeout: 15000 });
await page.waitForTimeout(600);
const r = await page.evaluate(() => {
  const s = (window).__paldyson;
  const w = s.world;
  const ox = Math.round(w.state.player.x / 48) - 10, oy = Math.round(w.state.player.y / 48) - 10;
  s.buildSys.deductCost = () => undefined;
  s.buildSys.place("research_lab", ox + 5, oy, 1);
  w.bAdd(w.state.buildings.find(b=>b.id==="research_lab"), "inB", "iron_ore", 4);
  w.bAdd(w.state.buildings.find(b=>b.id==="research_lab"), "inB", "coal", 4);
  for (let t = 0; t < 40; t++) s.buildSys.tick(0.25);
  const started = s.techSys.start("t_metallurgy");
  for (let t = 0; t < 40; t++) s.techSys.tick(0.25);
  const before = JSON.stringify(w.state.research);
  localStorage.setItem("paldyson_save_v1", JSON.stringify({ ...w.state, version: 2 }));
  const stored = JSON.parse(localStorage.getItem("paldyson_save_v1"));
  return { started, before, storedResearch: JSON.stringify(stored.research), storedVersion: stored.version };
});
console.log("in-session:", JSON.stringify(r));
await page.reload({ waitUntil: "networkidle" });
await page.waitForSelector("#s-cont", { timeout: 15000 });
const raw = await page.evaluate(() => JSON.parse(localStorage.getItem("paldyson_save_v1")).research);
console.log("after-reload raw storage:", JSON.stringify(raw));
await page.click("#s-cont");
await page.waitForFunction(() => (window).__paldyson?.world, null, { timeout: 15000 });
await page.waitForTimeout(500);
const after = await page.evaluate(() => JSON.stringify((window).__paldyson.world.state.research));
console.log("in-game after continue:", after);
await browser.close();
